<!-- <style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#message
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        /* height: 100%; */
    }
</style>
<div id="welcome">
<h1><?php echo $this->title ?></h1>
    <div id="name"> 
        <ul>
        <li><?php echo $this->message?></li>
        </ul>
    </div>
</div> -->
